using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using iNKORE.UI.WPF.Modern.Controls;
using SteamLuaManager.Services;

namespace SteamLuaManager.ViewModels;

public partial class ExtractionViewModel : ObservableObject
{
    private readonly ISteamDumperService _dumperService;
    private CancellationTokenSource? _cts;

    [ObservableProperty]
    private string _appId = "";

    [ObservableProperty]
    private bool _pinManifest;

    [ObservableProperty]
    private bool _isRunning;

    [ObservableProperty]
    private string _statusMessage = "就绪";

    public ObservableCollection<string> LogLines { get; } = [];

    public ExtractionViewModel(ISteamDumperService dumperService)
    {
        _dumperService = dumperService;
    }

    [RelayCommand]
    private void ClearLog()
    {
        LogLines.Clear();
    }

    [RelayCommand(AllowConcurrentExecutions = true)]
    private async Task StartExtractionAsync()
    {
        var id = AppId?.Trim();
        if (string.IsNullOrEmpty(id))
        {
            StatusMessage = "请输入 AppID";
            return;
        }

        if (!int.TryParse(id, out _))
        {
            StatusMessage = "AppID 必须为数字";
            return;
        }

        if (IsRunning)
        {
            _cts?.Cancel();
            return;
        }

        IsRunning = true;
        StatusMessage = "正在提取...";
        LogLines.Clear();
        _cts = new CancellationTokenSource();

        _dumperService.LogLineReceived += OnLogLine;
        PostLog($"开始提取AppID:{id}");

        try
        {
            var result = await Task.Run(() =>
                _dumperService.RunAsync(id, PinManifest, _cts.Token));

            if (result.Success && result.ExtractedFiles.Count > 0)
            {
                await Task.Run(() => MoveFiles(result.OutputDirectory, GetAppCacheDir(id), result));
                StatusMessage = $"提取完成，{result.ExtractedFiles.Count} 个文件";
                PostLog($"提取成功！文件已保存到：{result.OutputDirectory}");
                ShowOpenDirectoryPrompt(result.OutputDirectory);
            }
            else if (result.Success)
            {
                StatusMessage = "提取完成，未产生文件";
                PostLog("✅ 提取成功，但未找到输出文件");
            }
            else
            {
                StatusMessage = "提取失败";
                PostLog("提取失败");
                PostLog("提示：提取的游戏需 Steam 账号本身拥有正版游戏，如依旧失败请尝试取消版本固定");
            }
        }
        catch (OperationCanceledException)
        {
            StatusMessage = "已取消";
            PostLog("⏹️ 操作已取消");
        }
        catch (Exception ex)
        {
            StatusMessage = $"异常: {ex.Message}";
            PostLog($"❌ 异常: {ex.Message}");
        }
        finally
        {
            _dumperService.LogLineReceived -= OnLogLine;
            IsRunning = false;
            _cts?.Dispose();
            _cts = null;
        }
    }

    private void ShowOpenDirectoryPrompt(string directory)
    {
        _ = Application.Current.Dispatcher.BeginInvoke(new Action(async () =>
        {
            var dialog = new ContentDialog
            {
                Title = "提取完成",
                Content = new TextBlock
                {
                    Text = $"提取完成！文件已保存到:\n{directory}\n\n是否打开该目录？",
                    TextWrapping = TextWrapping.Wrap,
                    MaxWidth = 420
                },
                PrimaryButtonText = "打开目录",
                CloseButtonText = "关闭",
                DefaultButton = ContentDialogButton.Primary
            };
            if (await dialog.ShowAsync() == ContentDialogResult.Primary)
                Process.Start("explorer.exe", directory);
        }));
    }

    private void MoveFiles(string srcDir, string cacheDir, DumperResult result)
    {
        Directory.CreateDirectory(cacheDir);

        var luaFiles = result.ExtractedFiles
            .Where(f => f.EndsWith(".lua", StringComparison.OrdinalIgnoreCase))
            .ToList();

        var moved = new List<string>();

        foreach (var src in luaFiles)
        {
            var dest = Path.Combine(cacheDir, Path.GetFileName(src));
            try
            {
                var content = File.ReadAllText(src);
                var cleaned = content.Replace("-- Generated by SteamAppDumper (Author:pjy612)", "").TrimStart('\r', '\n');
                File.WriteAllText(dest, cleaned);
                File.Delete(src);
                moved.Add(dest);
            }
            catch (Exception ex)
            {
                PostLog($"⚠️ 移动失败 {Path.GetFileName(src)}: {ex.Message}");
            }
        }

        // Delete non-.lua temp files
        foreach (var src in result.ExtractedFiles)
        {
            if (!src.EndsWith(".lua", StringComparison.OrdinalIgnoreCase))
            {
                try { File.Delete(src); } catch { }
            }
        }

        try { Directory.Delete(srcDir, recursive: true); } catch { }

        result.OutputDirectory = cacheDir;
        result.ExtractedFiles = moved;
    }

    private static string GetAppCacheDir(string appId)
    {
        var baseDir = Path.Combine(
            AppDomain.CurrentDomain.BaseDirectory, "Cache", "Extracted");
        return Path.Combine(baseDir, appId);
    }

    private void OnLogLine(string message) => PostLog(message);

    private void PostLog(string message)
    {
        _ = Application.Current.Dispatcher.BeginInvoke(new Action(() => LogLines.Add(message)));
    }
}
