<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>SteamLuaManager</AssemblyName>
    <RootNamespace>SteamLuaManager</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Title>Fluent Steam Lua 管理工具</Title>
    <Product>Fluent Steam Lua 管理工具</Product>
    <Version>1.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\app.png" />
    <EmbeddedResource Include="Assets\Tools\SteamAppDumper.exe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

</Project>
